#!/bin/bash

SETTINGS=iptv.settings

echo "Use: 'source setenv user'"

if [[ -e iptv/settings_$1.py ]] ; then
    SETTINGS="iptv.settings_$1"
else
    echo "Config não encontrada."
fi

export DJANGO_SETTINGS_MODULE=${SETTINGS}
