#!/usr/bin/env python

import time
import sys

T=0.1

sys.stdout.write('Inicio\n')
sys.stdout.flush()
time.sleep(T)
sys.stdout.write('P1')
sys.stdout.flush()
for i in range(10):
	sys.stdout.write('*')
	sys.stdout.flush()
	time.sleep(T)
sys.stdout.write('Fim')
sys.stdout.flush()

